library IEEE;
library work;

use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.xina_ni_ft_pkg.all;
use work.xina_ft_pkg.all;

-- Write-phase datapath (LUT-optimized / low-reg):
--  * NO 32-bit LFSR state registers here
--  * Payload is generated by a tiny (default 8-bit) LFSR + small index inside tg_write_lfsr
--  * Index wraps naturally on overflow
--  * Re-initializes on every i_txn_start_pulse (uses STARTING_SEED)
entity tg_write_datapath is
  generic(
    p_AWID       : std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0) := (others => '0');
    p_LEN        : std_logic_vector(7 downto 0) := x"00";
    p_BURST      : std_logic_vector(1 downto 0) := "01";
    p_INIT_VALUE : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

    -- how many index bits to keep (wraps at 2**p_INDEX_BITS)
    p_INDEX_BITS : positive := 8
  );
  port(
    ACLK    : in  std_logic;
    ARESETn : in  std_logic;

    INPUT_ADDRESS : in  std_logic_vector(63 downto 0);
    STARTING_SEED : in  std_logic_vector(31 downto 0);

    -- from controller
    i_txn_start_pulse : in std_logic;
    i_wbeat_pulse     : in std_logic;

    -- optional external override (CONTROL only; kept for compatibility)
    i_ext_update_en : in std_logic := '0';
    i_ext_data_in   : in std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

    -- AXI constant fields (write address)
    AWID    : out std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0);
    AWADDR  : out std_logic_vector(c_AXI_ADDR_WIDTH - 1 downto 0);
    AWLEN   : out std_logic_vector(7 downto 0);
    AWBURST : out std_logic_vector(1 downto 0);

    -- write data
    WDATA   : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
    WLAST   : out std_logic;

    -- debug (payload word)
    o_lfsr_value : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0)
  );
end tg_write_datapath;

architecture rtl of tg_write_datapath is
  constant c_LFSR_BITS : positive := 8;
  signal w_word : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
begin
  -- Constant fields
  AWADDR  <= INPUT_ADDRESS(c_AXI_ADDR_WIDTH - 1 downto 0);
  AWID    <= p_AWID;
  AWLEN   <= p_LEN;
  AWBURST <= p_BURST;

  -- Single beat
  WLAST <= '1';

  -- Payload word from tiny generator
  WDATA        <= w_word;
  o_lfsr_value <= w_word;

  -- NOTE: i_ext_update_en/i_ext_data_in intentionally ignored here to save LUTs.
  -- If you need it later, re-add a mux *outside* and keep the generator unchanged.

  u_GEN: entity work.tg_write_lfsr
    generic map(
      p_LFSR_BITS  => c_LFSR_BITS,
      p_INDEX_BITS => p_INDEX_BITS,
      p_OUT_WIDTH  => c_AXI_DATA_WIDTH
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,

      i_init_pulse => i_txn_start_pulse,
      i_step_pulse => i_wbeat_pulse,

      i_seed => STARTING_SEED,

      o_word => w_word
    );

end rtl;
