library IEEE;
library work;

use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.xina_ni_ft_pkg.all;
use work.xina_ft_pkg.all;

-- Write datapath (low-FF, LUT-optimized):
--  * Payload generated by tiny PRNG (one 8-bit reg inside tg_write_lfsr)
--  * Re-seeded on EVERY i_txn_start_pulse (matches tb_tg_tm_lb_top iterations)
--  * Advanced only on i_wbeat_pulse (W handshake)
entity tg_write_datapath is
  generic(
    p_INIT_VALUE : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0')
  );
  port(
    ACLK    : in  std_logic;
    ARESETn : in  std_logic;

    INPUT_ADDRESS : in  std_logic_vector(63 downto 0);
    STARTING_SEED : in  std_logic_vector(31 downto 0);

    -- from controller
    i_txn_start_pulse : in std_logic;
    i_wbeat_pulse     : in std_logic;

    -- Optional CONTROL-only override (kept for compatibility; ignored)
    i_ext_update_en : in std_logic := '0';
    i_ext_data_in   : in std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

    -- AXI constant fields (write address)
    AWID    : out std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0);
    AWADDR  : out std_logic_vector(c_AXI_ADDR_WIDTH - 1 downto 0);
    AWLEN   : out std_logic_vector(7 downto 0);
    AWBURST : out std_logic_vector(1 downto 0);

    -- write data
    WDATA   : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
    WLAST   : out std_logic;

    -- debug
    o_lfsr_value : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0)
  );
end tg_write_datapath;

architecture rtl of tg_write_datapath is
  signal w_prng : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
begin
  AWADDR  <= INPUT_ADDRESS(c_AXI_ADDR_WIDTH - 1 downto 0);
  AWID    <= (others => '0');
  AWLEN   <= x"00";  -- 1 beat
  AWBURST <= "01";  -- INCR

  WLAST <= '1';

  u_PRNG: entity work.tg_write_lfsr
    generic map(
      p_OUT_WIDTH => c_AXI_DATA_WIDTH
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,
      i_init_pulse => i_txn_start_pulse,
      i_step_pulse => i_wbeat_pulse,
      i_seed  => STARTING_SEED,
      o_word  => w_prng
    );

  -- No 32-bit mux: ignore external override for LUT savings
  WDATA        <= w_prng;
  o_lfsr_value <= w_prng;

end rtl;
