library IEEE;
library work;

use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.xina_ni_ft_pkg.all;
use work.xina_ft_pkg.all;

-- Read-phase datapath (LUT-optimized / low-reg):
--  * Expected payload is generated by a tiny LFSR inside tm_read_lfsr
--  * No 32-bit LFSR state register here
--  * Comparator checks only 8 LSBs to save LUTs (still detects payload mismatch)
--  * Re-initializes on every i_txn_start_pulse
entity tm_read_datapath is
  generic(
    p_ARID       : std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0) := (others => '0');
    p_LEN        : std_logic_vector(7 downto 0) := x"00";
    p_BURST      : std_logic_vector(1 downto 0) := "01";
    p_INIT_VALUE : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

    -- how many index bits to keep (wraps at 2**p_INDEX_BITS)
    p_INDEX_BITS : positive := 8
  );
  port(
    ACLK    : in  std_logic;
    ARESETn : in  std_logic;

    INPUT_ADDRESS : in  std_logic_vector(63 downto 0);
    STARTING_SEED : in  std_logic_vector(31 downto 0);

    -- from controller
    i_txn_start_pulse : in std_logic;
    i_rbeat_pulse     : in std_logic;

    -- from AXI read data channel
    RDATA : in std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);

    -- AXI constant fields (read address)
    ARID    : out std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0);
    ARADDR  : out std_logic_vector(c_AXI_ADDR_WIDTH - 1 downto 0);
    ARLEN   : out std_logic_vector(7 downto 0);
    ARBURST : out std_logic_vector(1 downto 0);

    -- minimal comparator output
    o_mismatch : out std_logic;

    -- debug (expected full word)
    o_expected_value : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0)
  );
end tm_read_datapath;

architecture rtl of tm_read_datapath is
  constant c_LFSR_BITS : positive := 8;
  constant c_CMP_BITS  : positive := c_LFSR_BITS;

  signal w_expected : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
begin
  -- (c_CMP_BITS is fixed to 8, always fits a 32-bit AXI data width)

  -- Constant fields
  ARADDR  <= INPUT_ADDRESS(c_AXI_ADDR_WIDTH - 1 downto 0);
  ARID    <= p_ARID;
  ARLEN   <= p_LEN;
  ARBURST <= p_BURST;

  -- Expected word from tiny generator
  o_expected_value <= w_expected;

  u_GEN: entity work.tm_read_lfsr
    generic map(
      p_LFSR_BITS  => c_LFSR_BITS,
      p_INDEX_BITS => p_INDEX_BITS,
      p_OUT_WIDTH  => c_AXI_DATA_WIDTH
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,

      i_init_pulse => i_txn_start_pulse,
      i_step_pulse => i_rbeat_pulse,

      i_seed => STARTING_SEED,

      o_word => w_expected
    );

  -- Comparator only checks 8 LSBs to save LUTs.
  -- Trade-off: bit-flips in other bits are NOT detected.
  u_CMP: entity work.tm_read_compare
    generic map(
      p_WIDTH => c_CMP_BITS
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,

      i_init_pulse  => i_txn_start_pulse,
      i_check_pulse => i_rbeat_pulse,

      i_expected => w_expected(c_CMP_BITS-1 downto 0),
      i_rdata    => RDATA(c_CMP_BITS-1 downto 0),

      o_mismatch => o_mismatch
    );

end rtl;
