library IEEE;
library work;

use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.xina_ni_ft_pkg.all;
use work.xina_ft_pkg.all;

-- Read datapath (low-FF, LUT-optimized):
--  * Expected payload generated by tiny PRNG (one 8-bit reg inside tm_read_lfsr)
--  * Re-seeded on EVERY i_txn_start_pulse (matches tb_tg_tm_lb_top iterations)
--  * Advanced only on i_rbeat_pulse (R handshake)
--  * Comparator sticky flag is CLEARED on every transaction start
entity tm_read_datapath is
  generic(
    p_ARID       : std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0) := (others => '0');
    p_LEN        : std_logic_vector(7 downto 0) := x"00";
    p_BURST      : std_logic_vector(1 downto 0) := "01";
    p_INIT_VALUE : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0) := (others => '0')
  );
  port(
    ACLK    : in  std_logic;
    ARESETn : in  std_logic;

    INPUT_ADDRESS : in  std_logic_vector(63 downto 0);
    STARTING_SEED : in  std_logic_vector(31 downto 0);

    -- from controller
    i_txn_start_pulse : in std_logic;
    i_rbeat_pulse     : in std_logic;

    -- from AXI read data channel
    RDATA : in std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);

    -- AXI constant fields (read address)
    ARID    : out std_logic_vector(c_AXI_ID_WIDTH - 1 downto 0);
    ARADDR  : out std_logic_vector(c_AXI_ADDR_WIDTH - 1 downto 0);
    ARLEN   : out std_logic_vector(7 downto 0);
    ARBURST : out std_logic_vector(1 downto 0);

    o_mismatch : out std_logic;
    o_expected_value : out std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0)
  );
end tm_read_datapath;

architecture rtl of tm_read_datapath is
  signal w_expected : std_logic_vector(c_AXI_DATA_WIDTH - 1 downto 0);
begin
  ARADDR  <= INPUT_ADDRESS(c_AXI_ADDR_WIDTH - 1 downto 0);
  ARID    <= p_ARID;
  ARLEN   <= p_LEN;
  ARBURST <= p_BURST;

  u_PRNG: entity work.tm_read_lfsr
    generic map(
      p_OUT_WIDTH => c_AXI_DATA_WIDTH
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,
      i_init_pulse => i_txn_start_pulse,
      i_step_pulse => i_rbeat_pulse,
      i_seed  => STARTING_SEED,
      o_word  => w_expected
    );

  o_expected_value <= w_expected;

  u_CMP: entity work.tm_read_compare
    generic map(
      p_WIDTH => c_AXI_DATA_WIDTH
    )
    port map(
      ACLK    => ACLK,
      ARESETn => ARESETn,
      i_init_pulse  => i_txn_start_pulse,
      i_check_pulse => i_rbeat_pulse,
      i_expected => w_expected,
      i_rdata    => RDATA,
      o_mismatch => o_mismatch
    );

end rtl;
